[formatting]
line_length = 79

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.models]
displayed_models = []
custom_models = []

[mcp]
presets = []

[mcp.mcpServers]

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[runtime]
default_sql_output = "auto"
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
reactive_tests = true
on_cell_change = "autorun"
output_max_bytes = 8000000
default_auto_download = []
auto_reload = "autorun"
auto_instantiate = true

[package_management]
manager = "uv"

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_pylint = false
enable_pyflakes = false
enable_flake8 = false
enable_pydocstyle = false
enabled = true
enable_ruff = true
enable_mypy = true

[completion]
copilot = "github"
activate_on_typing = true

[snippets]
include_default_snippets = true
custom_paths = []

[display]
dataframes = "rich"
cell_output = "below"
theme = "dark"
default_table_page_size = 10
code_editor_font_size = 14
reference_highlighting = true
default_width = "medium"
default_table_max_columns = 50

[server]
follow_symlink = false
browser = "default"

[experimental]

[diagnostics]
